POST http://localhost:8080/reg
Content-Type: application/x-www-form-urlencoded

login=zhyb&password=12345678&name=Yauheni

###

POST http://localhost:8080/auth
Content-Type: application/x-www-form-urlencoded

login=noximt&password=12345

###

GET http://localhost:8080/change

###

POST http://localhost:8080/change
Content-Type: application/x-www-form-urlencoded

id=1&value=qwerty&type=pass

###

GET http://localhost:8080/calculate?x=10&y=7&optype=sum

###
